source 'https://rubygems.org'

ruby '2.7.5'
gem 'guard', '~> 2.18'
gem 'guard-minitest', '~> 2.4', '>= 2.4.6'
gem 'minitest', '~> 5.15'
gem 'simplecov', '~> 0.21.2'
gem 'terminal-notifier-guard'
gem 'terminal-notifier'
gem 'pry-byebug'
